server:
  port: 8888

spring:
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168

  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      pool-name: auth-pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048

jwt:
  life-time:
    access: 300
    refresh: 1800

  public-key: |
             -----BEGIN PUBLIC KEY-----
             -----END PUBLIC KEY-----

  private-key: |
             -----BEGIN PRIVATE KEY-----
             -----END PRIVATE KEY-----


health:
  config:
    enabled: false

management:
  health:
#    diskspace:
#      enabled: true
    db:
      enabled: true
#    refresh:
#      enabled: false
    defaults:
      enabled: false

  endpoint:
    health:
      show-details: always

#    loggers:
#      enabled: true

  endpoints:
    web:
      exposure:
        include: "health,prometheus"

#    jmx:
#      domain: com.procurement
#      exposure:
#        exclude: "*"

#  metrics:
#    distribution:
#      percentiles-histogram:
#        http:
#          server:
#            requests: true
#      sla:
#        http:
#          server:
#            requests: 1ms,5ms
#  server:
#    port: 9999
#  info:
#    git:
#      mode: full